### ISSUE TITLE
Progress on landscape makers

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/NeutralLandscapes.jl#11]
The list below is for housekeeping, let's add PR / usernames after the ones that are left to do.

## Done
- [x] planar gradient
- [x] edge gradient
- [x] no gradient
- [x] wave surface
- [x] distance gradient #13 
- [x] random rectangular cluster #12 
- [x] Perlin noise #18 
- [x] random cluster nearest neighbor #41
- [x] diamond square and mpd #19 
- [x] random element nearest neighbor #22

**Comment by rafaqz** [comment]
I can do "random cluster nearest neighbor" :))

**Comment by mkborregaard** [comment]
Do you want push access to the org @rafaqz ?

**Comment by rafaqz** [comment]
Sure. Thanks. 

How do you feel about an ImageMorphology.jl dep? It has the label and feature distance methods we need for nearest neighbor algs.

**Comment by mkborregaard** [comment]
Given that this is an end-user-facing package rather than a base package I don't see any issues with taking on deps. It's not exactly lightweight though - does NearestNeighbors.jl not do the trick? - let's continue that discussion under #14

**Comment by rafaqz** [comment]
@mkborregaard just tried pushing a perlin branch but was denied :pleading_face: 

Can someone give me push access?

**Comment by mkborregaard** [comment]
Did you accept the membership invite?

**Comment by mkborregaard** [comment]
You didn't, it seems, it's still listed as "pending"

**Comment by rafaqz** [comment]
Oops sorry, my github message feed is insane these days

**Comment by mkborregaard** [comment]
What's missing in addition to the algorithms?

- [x] classifyarra0
- [x] blendarrays
- [x] blendclusterarray
- [x] meanofcluster
- [x] exportasciigrid [wontfix]

and that's it, right?

**Comment by tpoisot** [comment]
@mkborregaard I think so - `exportasciigrid` is something I've done before (`readasc` as well) so I'll dig it up.

**Comment by tpoisot** [comment]
`ascii` in #26 -- this is `exportasciigrid`

**Comment by tpoisot** [comment]
So the last algo remaining is not the most friendly, because we need a sort of image segmentation code for it to work.

**Comment by mkborregaard** [comment]
is that ndimage.measurements.label?
I worked around that function call in `_clusterMean` but looking at it I don't think I did it right, so I'll just need to check that code again.

**Comment by tpoisot** [comment]
It can be solved with a heuristic as a temporary solution. That's nothing more than a constrained label propagation, and this tends to converge in a few iteration. I can try this and see if that performs well.

**Comment by mkborregaard** [comment]
Nice. Yeah I thought it could essentially be done single-pass but maybe I'm not understanding the full complexity of the issue

**Comment by rafaqz** [comment]
ImageMorphology.jl has this. Maybe just doing that PR to generalise it is less work.

**Comment by rafaqz** [comment]
So there is very little to it in ImageMorphology... except it uses traits like `coords_spatial` from ImageCore.jl. Again not even image related, but lots of image related deps.

It looks like we have to abstract everything not image related out of the Images.jl ecosystem at some stage. I think it's not much work technically and it's even their long-term intention, but getting all the PRs through and package registrations would be a lot of work. But ...someone has to do it some day - these methods are in Numpy, not some python image package.

**Comment by mkborregaard** [comment]
Update: I wasn't understanding the full complexity of the issue.
Anyway, pushing on ImageMorphology sounds like a good idea, if that org catches the ball and start running with it some of us could possibly help? Let's see how responsive they are.

**Comment by rafaqz** [comment]
I could do most of it honestly, they are really small changes. The main issue is getting agreement on moving the traits out of ImageCore.jl and to somewhere without all those depsendencies.

**Comment by mkborregaard** [comment]
I think the ImageMorphology is the right way to go honestly and it sounds like they are amenable to it. Honestly having them split and then Raf's fast code in Stencils would be a really awesome thing for the ecosystem.
Just because I'm stupid I did find it fun to try and implement a label function myself. I think I succeeded (and that it's OK efficient) - I could put that in a PR for now?

```julia
function _label(mat)
    rook = ((1, 0), (0, 1))
    m, n = size(mat)
    (m >= 3 && n >= 3) || error("The label algorithm requires the landscape to be at least 3 cells in each direction")
    
    # initialize objects and fill corners of ret
    ret = zeros(Int, m, n)
    clusters = Dict{Int, Int}()
    label = 0

    # run through the matrix and make clusters
    for j in axes(mat, 2), i in axes(mat, 1)
        same = [i - n[1] > 0 && j - n[2] > 0 && mat[i - n[1], j - n[2]] == mat[i, j] for n in rook]
        if count(same) == 0
            ret[i, j] = label += 1
            clusters[label] = label
        else
            vals = [ret[i - n[1], j - n[2]] for n in rook[same]]
            mi = minimum(vals)
            for v in vals
                clusters[v] = mi
            end
            ret[i, j] = mi
        end
    end
    
    # merge adjacent clusters with same value
    ncl = 0
    for i in eachindex(ret)
        ret[i] = _getval(clusters, ret[i])
        ncl = max(ncl, ret[i])
    end
    ncl, ret
end

function _getval(clusters, val)
    while true
        val2 = clusters[val]
        val2 == val && return val
        val = val2
    end
end
```
An example use
```julia
a = rand(DistanceGradient(rand(1:100, 3)), 10, 10)
b = classify!(copy(a), ones(4))
nc, c = _label(b)
plot(heatmap(a), heatmap(b), heatmap(c, fillcolor = :picasso), size = (1400, 400), layout = (1,3))
```
Two example runs
![_label](https://user-images.githubusercontent.com/8429802/108526735-c728c000-72d1-11eb-9613-f04db1dd1e82.png)
![_label2](https://user-images.githubusercontent.com/8429802/108526744-cb54dd80-72d1-11eb-8b17-aca07b0e63f4.png)

**Comment by tpoisot** [comment]
that looks like it works - let's PR this and if the ImageMorpho split happens we'll replace it?
